"use client";

import { Nanum_Gothic_Coding } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReactQueryProviders from "@/hook/useReactQuery";
import React from "react";
import { Toaster } from "@/components/ui/toaster";
import { usePreventBackNavigation } from "@/hook/usePreventBackNavigation";

const nanum = Nanum_Gothic_Coding({
  weight: "700",
  subsets: ["latin"],
});

// 메타데이터는 서버 컴포넌트에서만 사용 가능하므로 별도의 파일로 분리하거나 다른 방식으로 처리해야 합니다.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  usePreventBackNavigation();
  return (
    <html lang="en" className={nanum.className}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"
        />
      </head>
      <body className="">
        <div className="mx-auto flex h-[100vh] w-full max-w-[1400px] flex-col">
          <ReactQueryProviders>
            <Header />
            <main className="grow flex flex-col flex-1 overflow-hidden">
              {children}
              <Toaster />
            </main>
            <Footer />
          </ReactQueryProviders>
        </div>
      </body>
    </html>
  );
}
