import type { Metadata } from "next";
import { Nanum_Gothic, Nanum_Gothic_Coding } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const nanum = Nanum_Gothic_Coding({
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="game-container" className={nanum.className}>
        {/* <div id="overlay" /> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
